### ISSUE TITLE
Lier SVG et CSS

### ISSUE THREAD

**Issue by Alice1707** [eaa-3imd-2017/PORTUGAL#1]
Je rencontre un problème au niveau de mon css. J'aimerais qu'un div apparaisse au survol d'un pays.
J'ai mon div "espagnehover" dans mon html mais la class "espagne" se trouve dans le fichier europe.svg. Le navigateur ne comprends donc pas comment lier deux classes qui se trouvent dans deux fichiers différents.
j'aimerais arriver au résultat suivant :
.espagnehover { display: hidden)

.espagne:hover + .espagnehover { display:block}

Pouvez vous m'aider ?

**Comment by Alice1707** [comment]
J'ai trouvé ça, je ne sais pas si c'est une piste : https://github.com/mberneti/jquery-svg/

**Comment by Alice1707** [comment]
Merci je regarde ce soir 👍

**Comment by Alice1707** [comment]
J'ai regardé le code et je l'ai intégré dans mon code mais cela ne marche pas. Dois-je rajouter quelque chose dans le JavaScript ? Une classe ?

**Comment by ms-studio** [comment]
Etant donné qu'on accède le SVG "depuis l'extérieur", il faut que cela tourne sous HTTP. Il faut donc effectuer un essai sur MAMP.

**Comment by ms-studio** [comment]
On peut aussi le vérifier en ligne, ici : https://eaa-3imd-2017.github.io/PORTUGAL/index.html
