### ISSUE TITLE
JS media queries

### ISSUE THREAD

**Issue by Alice1707** [eaa-3imd-2017/PORTUGAL#4]
Dans mon projet, j'ai deux types de JavaScript : le hover pour le desktop et le clic pour le mobile. Comment dois je faire pour appliquer un code JavaScript à une certaine résolution d'écran ?
Merci d'avance

**Comment by Alice1707** [comment]
Ma deuxième question concerne la navigation en cliquant sur une zone de la carte. J'ai essayé de reprendre le code que vous avions fait pour la navigation du Menu et de l'intégrer à ma page svg-animate.js mais cela ne marche pas. Je pense que je ne cible pas mes éléments de la bonne façon.
J'aimerais que lorsque je clique sur la Suisse, cela ouvre le deuxième niveau, comme la navigation du menu.

**Comment by ms-studio** [comment]
Pour la question des MediaQueries et JavaScript, voici un exemple tiré d'un thème WordPress d'Elmastudio:

```javascript
if (document.documentElement.clientWidth > 680 && document.documentElement.clientWidth < 1260) {
  jQuery(document).ready(function(){
	// code ici...
  });
}
```

Une autre technique plus récente:

```javascript
var mq = window.matchMedia('@media all and (max-width: 700px)');
if(mq.matches) {
    // the width of browser is more than 700px
} else {
    // the width of browser is less than 700px
}
```

**Comment by Alice1707** [comment]
Je n'arrives pas à le faire fonctionner. Il enlève mes hover mais à toutes les tailles

**Comment by Alice1707** [comment]
Merci pour l'aide, cela fonctionne

**Comment by Alice1707** [comment]
J'ai deux problèmes : 

1) J'ai essayé de reprendre le code et de mettre max-width (pour la version mobile) mais cela ne marche pas, j'ai donc essayé de copié le JS sans MediaQueries pour qu'il apparaisse sur mobile mais cela ne marche pas non plus.

2) J'aimerais que sur mobile, le hover soit remplacé par un clic, j'ai donc essayé de mettre "onClik" ou "click" à la place de "MouseEnter" mais cela ne marche pas non plus
